### ISSUE TITLE
Crashing Server while interacting with other mods it seems. 

### ISSUE THREAD

**Issue by Zelioth** [izofar/takes-a-pillage#1]
Minecraft Version - 1.19.2
Forge Version - 43.1.25
Mod Version - 1.0.0  -1.19.2

Custom Mod Pack and Server : https://www.curseforge.com/minecraft/modpacks/friends-united

Added the mod to my custom mod pack and server yesterday in a update. Since that update we have had nothing but crashes from the the server involving "It Takes A Pillage" I'll post one or multiple reports. The Crash reports indicate Both a mod named "The BumbleZone" 
This mod wasn't causing any issues prior to the update of adding "It Takes A Pillage". I will also be posting this same crash information on their issue tracker to see if the issue is tracked on their end as well. 

I do not know how to recreate this issue. Players are saying they aren't interacting with anything to do with Pillagers. I hate to remove this mod so soon after adding it but if it continues I will have to remove it permanently 

[crash-2022-09-15_12.34.15-server.txt](https://github.com/izofar/takes-a-pillage/files/9576388/crash-2022-09-15_12.34.15-server.txt)
[crash-2022-09-15_12.06.50-server.txt](https://github.com/izofar/takes-a-pillage/files/9576389/crash-2022-09-15_12.06.50-server.txt)
[crash-2022-09-15_10.22.02-server.txt](https://github.com/izofar/takes-a-pillage/files/9576391/crash-2022-09-15_10.22.02-server.txt)

**Comment by TelepathicGrunt** [comment]
Looks like the mob effect event forge fires may have a null effect instance under certain situations. A null check is needed here in takes a pillage mod to prevent a crash with vanilla or other mods. I suspect drinking milk without any status effect will also cause this crash

https://github.com/izofar/takes-a-pillage/blob/a76c99a1b2c1c831a9c0c4e718a3880dc4665956/src/main/java/com/izofar/takesapillage/event/ModEntityEvents.java#L58

It’s also why vanilla Honey Bottle will also cause this crash because Honey Bottle calls removeEffects to remove poison. A null effect instance in the event is a valid case

**Comment by izofar** [comment]
> Looks like the mob effect event forge fires may have a null effect instance under certain situations. A null check is needed here in takes a pillage mod to prevent a crash with vanilla or other mods. I suspect drinking milk without any status effect will also cause this crash
> 
> https://github.com/izofar/takes-a-pillage/blob/a76c99a1b2c1c831a9c0c4e718a3880dc4665956/src/main/java/com/izofar/takesapillage/event/ModEntityEvents.java#L58
> 
> It’s also why vanilla Honey Bottle will also cause this crash because Honey Bottle calls removeEffects to remove poison. A null effect instance in the event is a valid case

That's right, good catch

**Comment by izofar** [comment]
Fixed on branch 1.19.x by commit [b04c5dc](https://github.com/izofar/takes-a-pillage/commit/b04c5dca54ff27a41483ae1cd800d9b11cec06c8)
