### ISSUE TITLE
ticking the skirmisher crashes the server

### ISSUE THREAD

**Issue by BomberDavi** [izofar/takes-a-pillage#16]
[crash-2023-01-25_14.22.42-server.txt](https://github.com/izofar/takes-a-pillage/files/10503879/crash-2023-01-25_14.22.42-server.txt)

**Comment by BomberDavi** [comment]
The server also crashed with a vindicator, theres a raid going on. Could there be any mod conflicts causing this? Do I have the wrong version installed? Thanks!

**Comment by izofar** [comment]
The issue is that one of the other mods is modifying `DoorInteractGoal.isOpen` with an uncancellable mixin. That would make their mod and mine incompatible. They also did not preface their mixin method with their modid, so I can't pick out which mod. 

 The only reason it crashed on my mod/entity was because the Skirmisher opened a door, a behavior which was implemented identically to other mobs with the same behavior.

Therefore, I will not be making any fix. If you can find out which mod in your pack modifies door-opening behavior, please let me know or the mod creator, so that we can inform him of better mixin practices.

**Comment by izofar** [comment]
Since you have the mod pack installed, you can follow [these instructions](https://gist.github.com/TelepathicGrunt/3784f8a8b317bac11039474012de5fb4#seeing-mixins-in-source-code) when running your game, then give me the `.mixins.out` file + the crash log
