### ISSUE TITLE
Pillager Camp vs. BoP Lavender Fields

### ISSUE THREAD

**Issue by AK-Chester** [izofar/takes-a-pillage#3]
![LavenderCamp](https://user-images.githubusercontent.com/112804655/191031095-f4afb034-c6b4-4615-90e6-e69e414236cb.jpg)
The Lavender Fields from Biomes O' Plenty might not be the best spot for a pillager camp (?) - lavender all over the place. Are there any plans for a config that'll allow blacklisting certain biomes? Love the mod, btw. :)

**Comment by izofar** [comment]
I agree that the flowers inside don't look too nice... I am working on a way to prevent decorative features from generating inside the structures. I don't want to remove the structures from the plains biomes because as more and more modded biomes are added to the game, my structures will be harder to find. Therefore, I add according to suitable terrain.

**Comment by AK-Chester** [comment]
Understandable. If you should find a way to prevent things like this from happening - f.e. the pillagers turning into a bunch of hippies - that would be even better, of course. I'm a sucker for peace and love but I don't think the pillagers are. 😆

**Comment by izofar** [comment]
Fixed: 1.19.2: [c7b81ae](https://github.com/izofar/takes-a-pillage/commit/c7b81ae3c9b1425a9627daa853b70f0af9cbdd31), 1.18.2: [7de592e](https://github.com/izofar/takes-a-pillage/commit/7de592ee776df4129d7cbca5d1fd4bbf2e67cc7a), 1.16.5: [7afe6fb](https://github.com/izofar/takes-a-pillage/commit/7afe6fbbdfd04cb2bbb6903ec0b14874b69e056e)
